Add multi-search federation
meilisearch/meilisearch-go pull request #563
Opened 2024-08-20 13:01 UTC by polyfloyd

# Pull Request

Fixes #573

## What does this PR do?
This PR adds support for the new federated search to be introduced in v1.10: https://github.com/meilisearch/meilisearch/releases/tag/v1.10.0-rc.0

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

2024-08-20 13:02 UTC, polyfloyd commented
Please note that I am running into an issue here: `unaccepted status code found: 400 expected: [200], MeilisearchApiError Message: Inside .queries[0]: Using pagination options is not allowed in federated queries.`

I think this patch is correct, so I'm opening this PR already. But I can not be 100% sure just yet

2024-08-20 13:16 UTC, curquiza commented
Hello @polyfloyd 
thanks for your PR, but v1.10 is not released yet. So I will review and merge a PR for federated once v1.10 is release 😊 

Thanks for your anticipation and involvement 😄

2024-08-20 13:21 UTC, polyfloyd commented
Found the cause of the error message, this Go library sets the pagination limit of each query to a default. I removed it for now so I can continue testing

2024-08-20 14:57 UTC, Ja7ad commented
@polyfloyd Thank you, currently you can change this PR to draft until release v1.10 and add issue for federation search.

2024-08-28 09:25 UTC, polyfloyd commented
Saw that there is an issue open now: #573

Will go over the checklist to see whether there is still something to be done

2024-08-28 09:34 UTC, Ja7ad commented
> Saw that there is an issue open now: #573
> 
> Will go over the checklist to see whether there is still something to be done

Please do this check list:

- [ ] write test stage for multi-search with federation
- [ ] add `_federation` for `SearchResponse`

```json
"_federation": {
        "indexUid": "comics",
        "queriesPosition": 1
      }
```

2024-08-28 09:36 UTC, polyfloyd commented
Thanks!

2024-08-28 09:42 UTC, Ja7ad requested changes

2024-08-28 09:42 UTC, Ja7ad commented on types.go
> +	// For federated results.
Please remove comment

2024-08-28 09:42 UTC, Ja7ad commented on types.go
>  	Results []SearchResponse `json:"results"`
Please add tag `omitempty`

2024-08-28 09:42 UTC, Ja7ad commented on types.go
> +	Hits               []interface{} `json:"hits"`
Please add tag `omitempty`

2024-08-28 09:42 UTC, Ja7ad commented on types.go
> +	ProcessingTimeMs   int64         `json:"processingTimeMs"`
Please add tag `omitempty`

2024-08-28 09:42 UTC, Ja7ad commented on types.go
> +	Offset             int64         `json:"offset"`
Please add tag `omitempty`

2024-08-28 09:42 UTC, Ja7ad commented on types.go
> +	Limit              int64         `json:"limit"`
Please add tag `omitempty`

2024-08-28 09:42 UTC, Ja7ad commented on types.go
> +	SemanticHitCount   int64         `json:"semanticHitCount"`
Please add tag `omitempty`

2024-08-28 16:03 UTC, Ja7ad commented
> Updated the commit title and added a test.
> 
> Adding `_federation` to SearchResponse does not seem correct? This object is present in each item of the `hits` array. See the expected payload of the new unit test to see what I mean

```go
type SearchResponse struct {
	Hits               []interface{}       `json:"hits"`
	EstimatedTotalHits int64               `json:"estimatedTotalHits,omitempty"`
	Offset             int64               `json:"offset,omitempty"`
	Limit              int64               `json:"limit,omitempty"`
	ProcessingTimeMs   int64               `json:"processingTimeMs"`
	Query              string              `json:"query"`
	FacetDistribution  interface{}         `json:"facetDistribution,omitempty"`
	TotalHits          int64               `json:"totalHits,omitempty"`
	HitsPerPage        int64               `json:"hitsPerPage,omitempty"`
	Page               int64               `json:"page,omitempty"`
	TotalPages         int64               `json:"totalPages,omitempty"`
	FacetStats         interface{}         `json:"facetStats,omitempty"`
	IndexUID           string              `json:"indexUid,omitempty"`
	Federation         *FederationResponse `json:"_federation,omitempty"`
}

type FederationResponse struct {
	IndexUID        string `json:"indexUid,omitempty"`
	QueriesPosition int64  `json:"queriesPosition,omitempty"`
}
```

2024-08-28 16:06 UTC, Ja7ad commented
> Updated the commit title and added a test.
> 
> Adding `_federation` to SearchResponse does not seem correct? This object is present in each item of the `hits` array. See the expected payload of the new unit test to see what I mean

Don't require any do for this.

2024-08-29 08:14 UTC, Ja7ad approved these changes

2024-08-29 08:15 UTC, Ja7ad commented
@polyfloyd please add `fixes #573` in PR description

2024-09-04 07:14 UTC, polyfloyd commented
@Ja7ad I have added the issue ref to the PR description

2024-09-18 14:30 UTC, Ja7ad commented
bors merge

Thank you!!

2024-09-18 14:32 UTC, merged