Update tests for MeiliSearch v0.15.0
meilisearch/meilisearch-go pull request #81
Opened 2020-09-29 14:31 UTC by curquiza

This PR:
- will fail in this CI until the MeiliSearch's release v0.15.0 is out
- should work locally with the [prerelease v0.15.0rc0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0rc0)

⚠️ This PR should not be merged until the MeiliSearch's release v0.15.0 is out.

2020-09-30 12:33 UTC, eskombro requested changes
Can you rename the branch `bump-meilisearch-v0.15` to `bump-meilisearch-v0.15.0`?

Otherwise, looks good to me :)

2020-09-30 13:15 UTC, curquiza commented
It would imply to close this PR and to create another. The point of this name is to force the CI to be passed before any merge into this branch. And the pattern for the name is `bump-meilisearch-v*` so it's ok 😉

2020-09-30 14:07 UTC, eskombro requested changes

2020-09-30 14:07 UTC, eskombro commented on client_search_test.go
> +	if len(resp.Hits) == 0 {
```suggestion
	if len(resp.Hits) != len(booksTest) {
```

2020-10-01 14:38 UTC, eskombro approved these changes

2020-10-01 14:39 UTC, merged