Update CI structure
meilisearch/meilisearch-go pull request #94
Opened 2020-11-04 18:20 UTC by curquiza

The goal is to separate the different checks.
Why? Currenlty, on `master`, if the linter check fails, we don't know if the tests or the build will fail.
With this separation, the build, the linter, and the integration tests will run in different jobs so, independally in different runners.

2020-11-04 18:23 UTC, curquiza commented
bors try

2020-11-05 12:47 UTC, eskombro requested changes
This seems like a good idea, but it also triggers 3 times the environment set, docker image pull, etc.

I think this problem could be adressed by just altering the order of the checks: linter should be the last check, we don't want (need) to test linting before knowing if the code is even compilable. So the checks could go in this order:

1. build
2. Test
3. Lint

This would address a big part of the problem without having to run 3 CI at every push.

WDYT @curquiza ?

A not on this PR:

- The go.mod file defines the version compatibility. It is currently set to 1.12, so test shouldn't be done in a different environment (or we can upgrade the go.mod, but I think this should be consistent).

2020-11-05 12:47 UTC, eskombro commented on .github/workflows/check.yml
> +    - name: Set up Go 1.13
```suggestion
    - name: Set up Go 1.12
```

2020-11-05 12:47 UTC, eskombro commented on .github/workflows/check.yml
> +        go-version: 1.13
```suggestion
        go-version: 1.12
```

2020-11-05 12:47 UTC, eskombro commented on .github/workflows/check.yml
> +        go-version: 1.13
```suggestion
        go-version: 1.12
```

2020-11-05 12:47 UTC, eskombro commented on .github/workflows/check.yml
> +        go-version: 1.13
```suggestion
        go-version: 1.12
```

2020-11-05 12:47 UTC, eskombro commented on .github/workflows/check.yml
> +    - name: Set up Go 1.13
```suggestion
    - name: Set up Go 1.12
```

2020-11-05 12:47 UTC, eskombro commented on .github/workflows/check.yml
> +    - name: Set up Go 1.13
```suggestion
    - name: Set up Go 1.12
```

2020-11-05 12:53 UTC, eskombro commented
Suggestion:

We could add a separate CI on MERGE ONLY testing different OS like this one: https://github.com/mvdan/github-actions-golang#github-actions-for-go and different go versions

The keep a simple CI on PUSH just to check build + test + lint

2020-11-05 12:54 UTC, eskombro reviewed
Suggestion:

We could add a separate CI on MERGE ONLY testing different OS like this one: https://github.com/mvdan/github-actions-golang#github-actions-for-go and different go versions

The keep a simple CI on PUSH just to check build + test + lint

2020-11-05 13:17 UTC, curquiza commented
The lint and the tests are 2 completely different and independent checks. Why should I wait for the tests are all green (a check that could be reallyyyy long for some SDKs) to see the errors of the linter? 
A test could fail but could have no link with the linter error. I should have the possibility to know all the errors at the same time. What is the advantage of hiding errors if we could avoid it with a more structured CI?

> This would address a big part of the problem without having to run 3 CI at every push.

It's not 3 CIs but 3 jobs 😉
What's the issue of running 3 jobs? Putting everything in the same job makes the job not really clear about its role, and less easy to read in the PR.
Here, as a contributor, I know clearly what is run: "linter", "integration-tests" and "go-build", and I know the separated result of each one.
Before, I just know "go-tests" was passed or not. Not really clear.

2020-11-05 13:41 UTC, eskombro commented
In this case, do you think we need a build job?

`go test ...` builds before testing, and if it can't perform a build, it throws a very clear error message:

<img width="737" alt="Screenshot 2020-11-05 at 14 40 26" src="https://user-images.githubusercontent.com/10339833/98248240-f6126480-1f74-11eb-96d4-9f5b08159be1.png">

Build in go is almost instant.

2020-11-05 13:41 UTC, curquiza commented
And yes, the `integration-tests` should be done in different go versions, but in another PR maybe 🙂

2020-11-05 13:43 UTC, curquiza commented
> In this case, do you think we need a build job?

Indeed, the build job is not needed thanks to the tests, I can remove it! Do you agree with this removal?

2020-11-05 13:45 UTC, eskombro commented
> And yes, the `integration-tests` should be done in different go versions, but in another PR maybe 🙂

I'll create an issue about it if you prefer

2020-11-05 13:46 UTC, curquiza commented
bors try

2020-11-05 13:48 UTC, eskombro approved these changes
🌮

2020-11-05 13:51 UTC, curquiza commented
bors merge

2020-11-05 13:52 UTC, merged